# MoveIt uses this configuration for controller management

trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  execution_pipeline:
    pipeline:
      - default_planner_request_adapters/AddTimeParameterization
  trajectory_duration_monitoring: true
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - pollibot_arm_controller
    - pusher_controller

  pollibot_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
    action_ns: follow_joint_trajectory
    default: true
  pusher_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_5
    action_ns: follow_joint_trajectory
    default: true