planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.5
  SBLkConfigDefault:
    type: geometric::SBL
    range: 0.5

pollibot_arm:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault
    - SBLkConfigDefault

workspace_parameters:
  min_x: -2.0
  max_x: 2.0
  min_y: -2.0
  max_y: 2.0
  min_z: -2.0
  max_z: 2.0

plan_request_params:
  planning_attempts: 3
  planning_pipeline: ompl
  max_velocity_scaling_factor: 0.8
  max_acceleration_scaling_factor: 0.8
  planning_time: 10.0

# planning_scene_monitor_options:
#         name: "planning_scene_monitor"
#         robot_description: "robot_description"
#         joint_state_topic: "/joint_states"
#         attached_collision_object_topic: "/moveit_py/planning_scene_monitor"
#         publish_planning_scene_topic: "/moveit_py/publish_planning_scene"
#         monitored_planning_scene_topic: "/moveit_py/monitored_planning_scene"
#         wait_for_initial_state_timeout: 10.0

# planning_pipelines:
#         # pipeline_names: ["ompl", "pilz_industrial_motion_planner", "chomp", "ompl_rrt_star"]
#         pipeline_names: ["ompl"]

# plan_request_params:
#         planning_attempts: 1
#         planning_pipeline: ompl
#         max_velocity_scaling_factor: 1.0
#         max_acceleration_scaling_factor: 1.0

# ompl_rrtc:
#         plan_request_params:
#                 planning_attempts: 1
#                 planning_pipeline: ompl
#                 planner_id: "RRTConnectkConfigDefault"
#                 max_velocity_scaling_factor: 1.0
#                 max_acceleration_scaling_factor: 1.0
#                 planning_time: 1.0

# ompl_rrt_star:
#         plan_request_params:
#                 planning_attempts: 1
#                 planning_pipeline: ompl_rrt_star
#                 planner_id: "RRTstarkConfigDefault"
#                 max_velocity_scaling_factor: 1.0
#                 max_acceleration_scaling_factor: 1.0
#                 planning_time: 1.5

# pilz_lin:
#         plan_request_params:
#                 planning_attempts: 1
#                 planning_pipeline: pilz_industrial_motion_planner
#                 planner_id: "PTP"
#                 max_velocity_scaling_factor: 1.0
#                 max_acceleration_scaling_factor: 1.0
#                 planning_time: 0.8

# chomp:
#         plan_request_params:
#                 planning_attempts: 1
#                 planning_pipeline: chomp
#                 max_velocity_scaling_factor: 1.0
#                 max_acceleration_scaling_factor: 1.0
#                 planning_time: 1.5
