sensors:
  - default_sensor
default_sensor:
  max_range: 1000.0
  max_update_rate: 1.0
  padding_offset: 0.0
  padding_scale: 1.0
  point_cloud_topic: /camera/depth/points
  point_subsample: 1
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater